# Generated by Django 5.1.2 on 2024-10-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume_education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_title', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=20)),
                ('education_description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Resume_experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_title', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=20)),
                ('experience_description', models.CharField(max_length=300)),
            ],
        ),
    ]
