# Generated by Django 5.1.2 on 2024-10-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_resume_experience_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume_education',
            name='education_title',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='resume_education',
            name='year',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='resume_experience',
            name='experience_title',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='resume_experience',
            name='year',
            field=models.CharField(max_length=80),
        ),
    ]
