# Generated by Django 5.1.2 on 2024-10-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_resume_education_education_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients_logo', models.ImageField(upload_to='clients_media')),
            ],
        ),
    ]
