# Generated by Django 5.1.2 on 2024-10-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='clients_logo',
            field=models.ImageField(upload_to='client_media'),
        ),
    ]
